# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Myeonghun Lee
description: >- # this means to ignore newlines until "baseurl:"
  AI, Bioinformatics, Cheminformatics
og_image: https://github.com/mhlee216/Protein_Protein_Interaction_Prediction_GCN/blob/main/Model_architecture.jpg # /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: glow216@naver.com
      link: mailto:glow216@naver.com
    #- name: WeChat
    #  value: YourWeChatUsername
    #  link: "#"
  follow:
    #- name: Twitter
    #  link: http://twitter.com/YourTwitterUsername
    #  username: "@YourTwitterUsername"
    #- name: Facebook
    #  link: http://facebook.com/YourFacebookUsername
    #- name: LinkedIn
    #  link: http://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      link: http://github.com/mhlee216
    #- name: Dribbble
    #  link: https://dribbble.com/YourDribbbleUsername
    #- name: RSS
    #  link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1




remote_theme : eliottvincent/bay

url : "https://mhlee216.github.io"
baseurl : "" 
