# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: MHLEE
description: >- # this means to ignore newlines until "baseurl:"
  AI, Bioinformatics, Cheminformatics
og_image: /assets/img/profile-pic.jpg
google_analytics: "G-9HTVQTM2EW"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    #- name: Blog

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: leemh216@gmail.com
      link: mailto:leemh216@gmail.com
    #- name: WeChat
    #  value: YourWeChatUsername
    #  link: "#"
  follow:
    #- name: Twitter
    #  link: http://twitter.com/YourTwitterUsername
    #  username: "@YourTwitterUsername"
    #- name: Facebook
    #  link: http://facebook.com/YourFacebookUsername
    #- name: LinkedIn
    #  link: http://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      link: http://github.com/mhlee216
    #- name: Dribbble
    #  link: https://dribbble.com/YourDribbbleUsername
    #- name: RSS
    #  link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1

remote_theme : eliottvincent/bay

url : "https://mhlee216.github.io"
baseurl : "" 


# Analytics
# analytics:
#   provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
#   google:
#     tracking_id          : "G-9HTVQTM2EW"
#     anonymize_ip         : # true, false (default)
