# Site settings
title:          Tale
description:    "Minimal Jekyll theme for storytellers"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Chester How
  url:          https://github.com/mhlee216
  email:        glow216@naver.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale



remote_theme : chesterhow/tale

url : "https://mhlee216.github.io"
baseurl : "" 
